name: Deploy to EC2

on:
  push:
    branches:
      - main  # Menyesuaikan dengan branch yang ingin di-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.169.187.139 >> ~/.ssh/known_hosts  # Menambahkan host ke known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no rizki@54.169.187.139 << 'EOF'
            cd /home/rizki/gitactions
            git pull origin main
            npm install --production
            pm2 restart all
          EOF
